"""Named constants and configuration values."""

from .constants import (
    # Project types
    PROJECT_TYPE_PYTHON,
    PROJECT_TYPE_JAVA,
    SUPPORTED_PROJECT_TYPES,

    # File extensions
    EXT_JSON,
    EXT_MD,
    EXT_MARKDOWN,
    EXT_PY,
    EXT_JAVA,
    EXT_YAML,
    EXT_YML,
    EXT_XML,
    EXT_TXT,
    DOCUMENT_EXTENSIONS,
    CONFIG_EXTENSIONS,
    MARKUP_EXTENSIONS,

    # Resource types
    RESOURCE_TYPE_ENTITY,
    RESOURCE_TYPE_WORKFLOW,
    RESOURCE_TYPE_FUNCTIONAL_REQUIREMENTS,
    VERSION_DIR_PREFIX,

    # Git constants
    GIT_CMD,
    GIT_STATUS,
    GIT_CONFIG,
    GIT_ADD,
    GIT_COMMIT,
    GIT_PUSH,
    GIT_REMOTE,
    GIT_PULL,
    GIT_CLONE,
    GIT_CHECKOUT,
    GIT_PORCELAIN_FLAG,
    GIT_ALL_FILES,
    GIT_ORIGIN,
    GIT_GET_URL,
    GIT_COMMIT_MESSAGE_FLAG,
    GIT_USER_NAME_KEY,
    GIT_USER_EMAIL_KEY,
    GIT_DEFAULT_USER_NAME,
    GIT_DEFAULT_USER_EMAIL,

    # CLI providers
    CLI_PROVIDER_AUGMENT,
    CLI_PROVIDER_CLAUDE,
    CLI_PROVIDER_GEMINI,
    SUPPORTED_CLI_PROVIDERS,

    # Build modes
    BUILD_MODE_TEST,
    BUILD_MODE_PRODUCTION,

    # File names
    FILE_POM_XML,
    FILE_REQUIREMENTS_TXT,
    FILE_PACKAGE_JSON,

    # Timeouts and intervals
    CLI_PROCESS_TIMEOUT,
    BUILD_PROCESS_TIMEOUT,
    COMMIT_TIMEOUT,
    AUTH_REFRESH_TIMEOUT,
    PROCESS_CHECK_INTERVAL,
    COMMIT_INTERVAL_DEFAULT,
    COMMIT_INTERVAL_BUILD,
    PROGRESS_UPDATE_INTERVAL,
    PROGRESS_MAX_BEFORE_COMPLETION,
    PROGRESS_COMPLETE,

    # Workflow files
    WORKFLOW_SCHEMA_FILENAME,
    WORKFLOW_EXAMPLE_FILENAME,
    WORKFLOW_PROMPT_TEMPLATE,

    # UI tab names
    TAB_ENTITIES,
    TAB_WORKFLOWS,
    TAB_REQUIREMENTS,
    TAB_CLOUD,
    VALID_CANVAS_TABS,

    # Git status messages
    GIT_MSG_NOTHING_TO_COMMIT,
    GIT_MSG_WORKING_TREE_CLEAN,
    GIT_STATUS_MODIFIED,
    GIT_STATUS_ADDED,
    GIT_STATUS_DELETED,
    GIT_STATUS_RENAMED,
    GIT_STATUS_COPIED,
    GIT_STATUS_UNTRACKED,

    # Diff categories
    DIFF_CATEGORY_MODIFIED,
    DIFF_CATEGORY_ADDED,
    DIFF_CATEGORY_DELETED,
    DIFF_CATEGORY_UNTRACKED,

    # Repository information
    DEFAULT_REPO_OWNER,
    PUBLIC_REPO_PYTHON,
    PUBLIC_REPO_JAVA,

    # Log file naming
    LOG_PREFIX_BUILD,
    LOG_PREFIX_CODEGEN,
    LOG_SUFFIX_TEMP,
    LOG_EXTENSION,

    # String truncation
    TRUNCATE_LENGTH_SHORT,
    TRUNCATE_LENGTH_MEDIUM,
    TRUNCATE_LENGTH_LONG,

    # File limits
    MAX_CHANGED_FILES_IN_METADATA,

    # Error messages
    STOP_ON_ERROR,
)

__all__ = [
    # Project types
    "PROJECT_TYPE_PYTHON",
    "PROJECT_TYPE_JAVA",
    "SUPPORTED_PROJECT_TYPES",

    # File extensions
    "EXT_JSON",
    "EXT_MD",
    "EXT_MARKDOWN",
    "EXT_PY",
    "EXT_JAVA",
    "EXT_YAML",
    "EXT_YML",
    "EXT_XML",
    "EXT_TXT",
    "DOCUMENT_EXTENSIONS",
    "CONFIG_EXTENSIONS",
    "MARKUP_EXTENSIONS",

    # Resource types
    "RESOURCE_TYPE_ENTITY",
    "RESOURCE_TYPE_WORKFLOW",
    "RESOURCE_TYPE_FUNCTIONAL_REQUIREMENTS",
    "VERSION_DIR_PREFIX",

    # Git constants
    "GIT_CMD",
    "GIT_STATUS",
    "GIT_CONFIG",
    "GIT_ADD",
    "GIT_COMMIT",
    "GIT_PUSH",
    "GIT_REMOTE",
    "GIT_PULL",
    "GIT_CLONE",
    "GIT_CHECKOUT",
    "GIT_PORCELAIN_FLAG",
    "GIT_ALL_FILES",
    "GIT_ORIGIN",
    "GIT_GET_URL",
    "GIT_COMMIT_MESSAGE_FLAG",
    "GIT_USER_NAME_KEY",
    "GIT_USER_EMAIL_KEY",
    "GIT_DEFAULT_USER_NAME",
    "GIT_DEFAULT_USER_EMAIL",

    # CLI providers
    "CLI_PROVIDER_AUGMENT",
    "CLI_PROVIDER_CLAUDE",
    "CLI_PROVIDER_GEMINI",
    "SUPPORTED_CLI_PROVIDERS",

    # Build modes
    "BUILD_MODE_TEST",
    "BUILD_MODE_PRODUCTION",

    # File names
    "FILE_POM_XML",
    "FILE_REQUIREMENTS_TXT",
    "FILE_PACKAGE_JSON",

    # Timeouts and intervals
    "CLI_PROCESS_TIMEOUT",
    "BUILD_PROCESS_TIMEOUT",
    "COMMIT_TIMEOUT",
    "AUTH_REFRESH_TIMEOUT",
    "PROCESS_CHECK_INTERVAL",
    "COMMIT_INTERVAL_DEFAULT",
    "COMMIT_INTERVAL_BUILD",
    "PROGRESS_UPDATE_INTERVAL",
    "PROGRESS_MAX_BEFORE_COMPLETION",
    "PROGRESS_COMPLETE",

    # Workflow files
    "WORKFLOW_SCHEMA_FILENAME",
    "WORKFLOW_EXAMPLE_FILENAME",
    "WORKFLOW_PROMPT_TEMPLATE",

    # UI tab names
    "TAB_ENTITIES",
    "TAB_WORKFLOWS",
    "TAB_REQUIREMENTS",
    "TAB_CLOUD",
    "VALID_CANVAS_TABS",

    # Git status messages
    "GIT_MSG_NOTHING_TO_COMMIT",
    "GIT_MSG_WORKING_TREE_CLEAN",
    "GIT_STATUS_MODIFIED",
    "GIT_STATUS_ADDED",
    "GIT_STATUS_DELETED",
    "GIT_STATUS_RENAMED",
    "GIT_STATUS_COPIED",
    "GIT_STATUS_UNTRACKED",

    # Diff categories
    "DIFF_CATEGORY_MODIFIED",
    "DIFF_CATEGORY_ADDED",
    "DIFF_CATEGORY_DELETED",
    "DIFF_CATEGORY_UNTRACKED",

    # Repository information
    "DEFAULT_REPO_OWNER",
    "PUBLIC_REPO_PYTHON",
    "PUBLIC_REPO_JAVA",

    # Log file naming
    "LOG_PREFIX_BUILD",
    "LOG_PREFIX_CODEGEN",
    "LOG_SUFFIX_TEMP",
    "LOG_EXTENSION",

    # String truncation
    "TRUNCATE_LENGTH_SHORT",
    "TRUNCATE_LENGTH_MEDIUM",
    "TRUNCATE_LENGTH_LONG",

    # File limits
    "MAX_CHANGED_FILES_IN_METADATA",

    # Error messages
    "STOP_ON_ERROR",
]
